### PR TITLE
fixes #3609 sdk terminator race fixes and preferred-leader raft

### LINKED ISSUE #3609: Stabilize terminator creation test for 2.0

### PR DESCRIPTION
**Pull request by plorenz**
- removes legacy v1 terminator code path; all terminators now use v2 flow
    - refactors edgeTerminator.close() to decouple SDK notification from control plane notification
    - adds pending SDK close notification queue with retry when channel is busy
    - adds post-create inspect mechanism that verifies SDK still holds the bind after terminator creation
    - queues second post-create inspect when establishment takes >30s to catch SDK timeout races
    - detects and discards stale reordered binds on the same connection by comparing connIds
    - re-establishes replacement terminators when a delete/create race is detected
    - eliminates IsEntityPresent pre-filter in removeTerminatorsHandler to prevent raft ordering races
    - fixes ValidateTerminators to query identities from the correct manager with the correct filter field
    - adds postCreate flag to ValidateTerminatorsV2Request so routers skip redundant SDK inspect
    - returns retry-later (nil result) from router validation when inspect is temporarily unavailable
    - blocks SyncAllSubscribers until completion and guards RouterDataModel replacement with in-progress flag
    - fixes InheritLocalData to enable service access tracking for all subscribed identities
    - adds Services.Has check in GetServiceAccessPolicies to prevent false policy grants
    - validates policy-to-identity associations in ValidateServicePolicies
    - adds `ziti agent tunnel dump-sdk` command for SDK context inspection via IPC agent
    - adds `ziti fabric inspect sdk` command to query SDK context through routers
    - fixes --expected-per-host CLI flag binding in validate terminators command
    - changes bind-access-lost retry hint from NotRetriable to RetryStartOver
    - moves trace route response and xgress close handling off channel handler goroutine
    - fixes listTerminators test helper to URL-encode filter parameter
    - improves sdk-hosting-test validation resilience with login and query retries
    - adds terminator_create_flow.md documenting the full lifecycle across SDK, router, and controller
    - adds detailed logging for data model sync, service access tracking, and subscriber change detection

### CODE REVIEW

File: common/subscriber.go [hunk 1]
```diff
@@ -347,6 +348,26 @@ func (self *IdentitySubscription) checkForChanges(rdm *RouterDataModel) {
...
+				log.WithField("lostServiceId", svcId).
+					WithField("lostServiceName", service.GetName()).
+					WithField("trackingEnabled", newIdentity.serviceAccessTrackingEnabled.Load()).
+					WithField("serviceAccessCount", len(newIdentity.ServiceAccess)).
+					WithField("servicePolicyCount", len(newIdentity.ServicePolicies)).
+					WithField("serviceAccess", serviceAccessKeys).
+					WithField("servicePolicies", servicePolicyKeys).
+					WithField("oldServiceCount", len(oldServices)).
+					WithField("newServiceCount", len(newServices)).
+					Warn("service access lost detected during checkForChanges")
```
Comment (andrewpmartinez) [inline common/subscriber.go]: Is this really needed as a warning? It seems like this would happen normally.

File: router/state/manager.go [hunk 2]
```diff
@@ -917,6 +918,9 @@ func (self *ManagerImpl) pubKeyLookup(token *jwt.Token) (any, error) {
 // RouterDataModel returns the current router data model containing
 // network topology and policy information.
 func (self *ManagerImpl) RouterDataModel() *common.RouterDataModel {
+	for self.rmdReplaceInProgress.Load() {
+		time.Sleep(100 * time.Millisecond)
```
Comment (andrewpmartinez) [inline router/state/manager.go:925]: This seems awfully hacky.

File: common/subscriber.go (hunk 1 above)
Comment (plorenz) [reply common/subscriber.go]: Debug code from when I was trying to track down a bug where identities would temporarily lose access to services, even though the model hadn't changed. Removing.

File: router/state/manager.go (hunk 2 above)
Comment (plorenz) [reply router/state/manager.go:925]: It fixes a race condition where we get access to a partially initialized rdm instance. I could add more complicated machinery with a notify channel if the replace is in progress, but it's something that should happen rarely and the logic would be harder to follow and get right. I felt like this was the best solution given those circumstances. Do you have a different approach that doesn't add a bunch of complexity?

File: router/xgress_edge/hosted.go [hunk 3]
```diff
@@ -740,18 +967,17 @@ func (self *hostedServiceRegistry) checkForExistingListenerId(terminator *edgeTe
...
 		resultC:    make(chan invalidTerminatorRemoveResult, 1),
-		notifyCtrl: notifyCtrl,
 	}
 	self.queue(event)
 
 	select {
 	case result := <-event.resultC:
 		return result
-	case <-time.After(100 * time.Millisecond):
+	case <-time.After(250 * time.Millisecond):
```
Comment (andrewpmartinez) [inline router/xgress_edge/hosted.go]: Magical. I don't even know why this was increased.

File: router/xgress_edge/hosted.go [hunk 4]
```diff
@@ -794,7 +1020,7 @@ func (self *inspectTerminatorsEvent) handle(registry *hostedServiceRegistry) {
 			Precedence:      terminator.precedence.String(),
 			AssignIds:       terminator.assignIds,
 			UseSdkXgress:    terminator.useSdkXgress,
-			V2:              terminator.v2,
+			V2:              true,
```
Comment (andrewpmartinez) [inline router/xgress_edge/hosted.go]: To be clear, the terminators aren't v1/v2 its what the router supports? I am worried about mixed networks.

File: router/xgress_edge/listener.go [hunk 5]
```diff
@@ -215,6 +223,114 @@ func (listener *listener) submitResponse(resultCh chan *sdkCircuitResult, result
...
 }
 
+type sdkContextResult struct {
+	identityId string
+	connId     string
+	err        error
+	context    any
+}
+
+func (listener *listener) getSdkContext(identityId string) any {
```
Comment (andrewpmartinez) [inline router/xgress_edge/listener.go:233]: Why not an interface that can do generic (for example, []byte) marshalling/unmarshalling? I understand this is probably a re-applied pattern, but I am curious.

File: router/xgress_edge/listener.go [hunk 6]
```diff
@@ -335,12 +451,14 @@ func (self *edgeClientConn) handleBindAccessLost(service *common.IdentityService
 	for _, terminator := range terminators {
 		log.WithField("terminatorId", terminator.terminatorId).
 			Info("bind access to service, closing terminator")
-		err := &EdgeError{
+		edgeErr := &EdgeError{
 			Message:   "bind access lost",
 			Code:      sdkedge.ErrorCodeAccessDenied,
-			RetryHint: sdkedge.RetryNotRetriable,
+			RetryHint: sdkedge.RetryStartOver, // switch back to start over once timing issues are resolved
```
Comment (andrewpmartinez) [inline router/xgress_edge/listener.go:457]: Why the swap from "not retriable" to "start over"? Does start over mean "verify you have access again"?

File: router/xgress_router/factory.go [hunk 7]
```diff
@@ -30,9 +30,11 @@ type Dialer interface {
 	IsTerminatorValid(id string, destination string) bool
 }
 
+type InspectResult int
```
Comment (andrewpmartinez) [inline router/xgress_router/factory.go]: Was this ever used?

File: router/xgress_edge/hosted.go [hunk 8]
```diff
@@ -421,6 +435,217 @@ func (self *hostedServiceRegistry) queueRemoveTerminatorUnchecked(terminator *ed
...
+		registry.notifyCloseSet[idgen.MustNewUUIDString()] = self.notification
+	}
+}
+
+func (self *hostedServiceRegistry) addPendingSdkCloseNotification(terminator *edgeTerminator, reason string, edgeErr *EdgeError) {
+	self.notifyCloseSet[idgen.MustNewUUIDString()] = &pendingSdkCloseNotification{
+		terminator: terminator,
+		reason:     reason,
+		edgeErr:    edgeErr,
+	}
```
Comment (andrewpmartinez) [inline router/xgress_edge/hosted.go:472]: If this is called twice, does it just add two close notifies, as the UUIDs will always be different?

File: router/xgress_edge/hosted.go (hunk 4 above)
Comment (plorenz) [reply router/xgress_edge/hosted.go]: v1/v2 is which versions of the create terminator operation the controller supports, and since these are v2 routers which must talk to v2 controllers, we know we'll always be used the v2 create terminator operation

File: router/xgress_edge/hosted.go [hunk 9]
```diff
@@ -421,6 +435,217 @@ func (self *hostedServiceRegistry) queueRemoveTerminatorUnchecked(terminator *ed
...
+}
+
+func (self *hostedServiceRegistry) ensureSdkCloseSent(terminator *edgeTerminator, reason string, edgeErr *EdgeError) {
+	self.ensureSdkCloseSentInner(terminator, reason, edgeErr, false)
+}
+
+func (self *hostedServiceRegistry) ensureSdkCloseSentInner(terminator *edgeTerminator, reason string, edgeErr *EdgeError, queueDirect bool) {
```
Comment (andrewpmartinez) [inline router/xgress_edge/hosted.go]: `queueDirect` is a bit oblique as a naive reader. It toggles between queue and addPending.

File: router/state/manager.go (hunk 2 above)
Comment (andrewpmartinez) [reply router/state/manager.go:925]: That seems like a good comment for that line then.

File: router/xgress_edge/listener.go (hunk 5 above)
Comment (plorenz) [reply router/xgress_edge/listener.go:233]: It's called from the `listener.Inspect() any` API, so it's obeying that contract. The assumption is that the types are marshallable to JSON. I don't think there's an interface for that. The inspect system has grown somewhat organically over time and could probably use an overhaul

File: router/xgress_edge/listener.go (hunk 6 above)
Comment (plorenz) [reply router/xgress_edge/listener.go:457]: That bug that caused service loss meant that if we sent NoRetriable, the sdk would never retry. Because the sdk gets service updates from another path, it never thought it lost access. So unless you're getting access updates from the same path, there are coherency issues with sending 'do not retry'.

Yes, start over means redo access checks.

File: router/xgress_router/factory.go (hunk 7 above)
Comment (plorenz) [reply router/xgress_router/factory.go]: Removed

File: router/xgress_edge/hosted.go (hunk 8 above)
Comment (plorenz) [reply router/xgress_edge/hosted.go:472]: It does. However, we can't necessarily key by terminator as terminators can be replaced and the id can be re-used. We can't use the virtual conn id, because those aren't unique across routers. If we do happen to send multiple, it should be harmless, since the second close will be ignored. We could probably use a combination of terminator id and virtual conn id. I'll add a comment

File: router/xgress_edge/hosted.go (hunk 9 above)
Comment (plorenz) [reply router/xgress_edge/hosted.go]: I renamed it to `inEventLoop`

File: router/state/manager.go (hunk 2 above)
Comment (plorenz) [reply router/state/manager.go:925]: done

File: common/subscriber.go (hunk 1 above)
Comment (plorenz) [reply common/subscriber.go]: done

File: router/xgress_edge/hosted.go (hunk 3 above)
Comment (plorenz) [reply router/xgress_edge/hosted.go]: added a comment

File: router/xgress_edge/hosted.go (hunk 8 above)
Comment (plorenz) [reply router/xgress_edge/hosted.go:472]: done
