### PR TITLE
Fix startup panic if tunneler is not enabled. Fixes #2947. If tunneler is enabled don't require edge. Fixes #2948

### LINKED ISSUE #2947: Panic on router started up if edge/tunnel bindings not configured
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x128 pc=0x2e21d13]
goroutine 97 [running]:
github.com/openziti/ziti/common.(*RouterDataModel).GetTerminatorIdCache(...)
github.com/openziti/ziti/common/router_data_model.go:1161
github.com/openziti/ziti/router/xgress_edge_tunnel_v2.(*hostedServiceRegistry).pruneTerminatorIdCache(0xc000470150)
github.com/openziti/ziti/router/xgress_edge_tunnel_v2/hosted.go:124 +0x33
github.com/openziti/ziti/router/xgress_edge_tunnel_v2.(*hostedServiceRegistry).run(0xc000470150)
github.com/openziti/ziti/router/xgress_edge_tunnel_v2/hosted.go:98 +0x254
created by github.com/openziti/ziti/router/xgress_edge_tunnel_v2.newHostedServicesRegistry in goroutine 39
github.com/openziti/ziti/router/xgress_edge_tunnel_v2/hosted.go:53 +0x2d6
```

This is caused by some tunneler code running on startup whether or not the tunneler is enabled.

### LINKED ISSUE #2948: Allow ER/T to run without edge listener
Tunneler in the router should not require the edge listener to be enabled.

### PR DESCRIPTION
**Pull request by plorenz**

### CODE REVIEW

File: router/test/single_router_perf_test.go [hunk 1]
```diff
@@ -146,8 +147,13 @@ func Test_SingleRouterPerf(t *testing.T) {
 
 	registry := metrics.NewUsageRegistry("router", nil, closeNotify)
 	registry.StartReporting(&eventSink{}, time.Minute, 10)
+<<<<<<< Updated upstream
```
Comment (qrkourier) [inline router/test/single_router_perf_test.go:150]: fyi

Comment (plorenz) [reply router/test/single_router_perf_test.go]: fixed, thank you for spotting that

**Review by andrewpmartinez — APPROVED** [review]
