### PR TITLE
fix cli login with file; resolves #3378

### LINKED ISSUE #3378: login with file stopped working
Something changed on the main branch and logging in with an identity file no longer works.

Expected:

```bash
$ ziti edge login edge.bingnet.cloud:53 --file ziti-admin.json 
Saving identity 'default' to /home/kbingham/.config/ziti/ziti-cli.json
```

Observed:

```bash
$ ziti edge login --file /opt/openziti/etc/identities/bingnet1-mira.json    
Error: invalid controller URL supplied
```

### PR DESCRIPTION
**Pull request by qrkourier**
## Summary

Fixed `ziti edge login --file` to use the URL from the identity file instead of failing with "invalid controller URL supplied".

### Root Cause

[addHttpsIfNeeded("")](cci:1://file:///home/kbingham/Sites/netfoundry/github/ziti/ziti/cmd/edge/login.go:822:0-827:1) was converting empty strings to `"https://"`, which happened in two places early in the login flow ([terminatorId()](cci:1://file:///home/kbingham/Sites/netfoundry/github/ziti/ziti/cmd/edge/login.go:510:0-520:1) and [PopulateFromCache()](cci:1://file:///home/kbingham/Sites/netfoundry/github/ziti/ziti/cmd/edge/login.go:554:0-588:1)). This caused the code to skip extracting the URL from the identity file.

### Fix

Added guards to prevent calling [addHttpsIfNeeded()](cci:1://file:///home/kbingham/Sites/netfoundry/github/ziti/ziti/cmd/edge/login.go:822:0-827:1) on empty strings in three locations:
1. **[terminatorId()](cci:1://file:///home/kbingham/Sites/netfoundry/github/ziti/ziti/cmd/edge/login.go:510:0-520:1)** - Only call if `o.ControllerUrl != ""`
2. **[PopulateFromCache()](cci:1://file:///home/kbingham/Sites/netfoundry/github/ziti/ziti/cmd/edge/login.go:554:0-588:1)** - Only call if `o.ControllerUrl != ""`
3. **[addHttpsIfNeeded()](cci:1://file:///home/kbingham/Sites/netfoundry/github/ziti/ziti/cmd/edge/login.go:822:0-827:1)** - Return empty string unchanged

This ensures `o.ControllerUrl` stays empty when no URL is provided, allowing the identity file URL to be correctly extracted.

### CODE REVIEW

File: ziti/cmd/edge/login.go [hunk 1]
```diff
@@ -509,7 +509,9 @@ func (self *yesNoFilter) Accept(s string) bool {
 }
 
 func (o *LoginOptions) terminatorId() string {
-	o.ControllerUrl = addHttpsIfNeeded(o.ControllerUrl)
+	if o.ControllerUrl != "" {
```
Comment (dovholuknf) [inline ziti/cmd/edge/login.go]: these if's aren't needed since addHttpsIfNeeded does this

File: tests/cli_tests/login_test_import.yml [hunk 2]
```diff
@@ -7,7 +7,7 @@
       "configType": "@intercept.v1",
       "data": {
         "addresses": [
-          "mgmt.ziti"
+          "mgmt.ziti.internal"
```
Comment (dovholuknf) [inline tests/cli_tests/login_test_import.yml]: _eyeroll_... it's a test
