### PR TITLE
Fix peer connect panic. Fixes #2173

### LINKED ISSUE #2173: panic on HA peer connect
```
panic: runtime error: index out of range [0] with length 0
goroutine 313 [running]:
{0xc0026d0038, 0x1, 0x1})
github.com/openziti/ziti/controller/model/controller_manager.go:234 +0x178f
github.com/openziti/ziti/controller/env.(*Broker).AcceptClusterEvent(0xc00243eac0, 0xc00331c720)
github.com/openziti/ziti/controller/env/broker.go:94 +0x8e
github.com/openziti/ziti/controller/events.(*Dispatcher).AcceptClusterEvent.func1()
github.com/openziti/ziti/controller/events/dispatcher_cluster.go:36 +0x9a
created by github.com/openziti/ziti/controller/events.(*Dispatcher).AcceptClusterEvent in goroutine 65
github.com/openziti/ziti/controller/events/dispatcher_cluster.go:34 +0x67
```

### PR DESCRIPTION
**Pull request by plorenz**

### CODE REVIEW

File: controller/model/controller_manager.go [hunk 1]
```diff
@@ -231,12 +231,14 @@ func (self *ControllerManager) PeersConnected(peers []*event.ClusterPeer) {
 	selfAsPeer := self.getCurrentAsClusterPeer()
 	peerFingerprints := ""
 	for _, peer := range peers {
-		fingerprint := nfpem.FingerprintFromCertificate(peer.ServerCert[0])
+		if len(peer.ServerCert) > 0 {
```
Comment (dovholuknf) [inline controller/model/controller_manager.go:234]: maybe a nit, but why not just test for nil instead of finding the len ?

**Review by dovholuknf — APPROVED** [review]
just a small question wrt nil vs len checking

File: controller/model/controller_manager.go (hunk 1 above)
Comment (ekoby) [reply controller/model/controller_manager.go:234]: covers both cases: `nil` and empty
